name: HTML Check 2
on:
  pull_request:
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Requried will all actions
    - name: HTML5 Validator
      uses: Cyb3r-Jak3/html5validator-action@v7.0.0
      with:
        root: html/
        css: true
    - name: Label when approved
      uses: pullreminders/label-when-approved-action@master
      env:
        APPROVALS: "1"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ADD_LABEL: "approved"
